Resource:
CodeDeploy: 
  Type: AWS::CodeDeploy::Application
  Properties:
    ApplicationName: csye6225-webapp
    ComputePlatform: EC2/On-premises


CodeDeploymentGroup:
  Type: AWS::CodeDeploy::DeploymentGroup
  Properties:
    ApplicationName: !Ref CodeDeploy
    AutoRollbackConfiguration:
      Enabled: 'true'
      Events:
        - DEPLOYMENT_FAILURE
    DeploymentConfigName: CodeDeployDefault.AllAtOnce
    DeploymentGroupName: csye6225-webapp-deployment
    DeploymentStyle:
      DeploymentType: In-place
    Ec2TagSet:
      - Key: csye6225_key
        Value: csye6225_value
        Type: KEY_AND_VALUE
    ServiceRoleArn: 
      Fn::GetAtt: [ CodeDeployServiceRole, Arn ]
